### ISSUE TITLE
Proptype warning when adding componentprop

### ISSUE THREAD

**Issue by bardsol** [asbjornh/react-flip-motion#4]
`let Col3 = ({ children }) =>
			<Col type="3">
				{children}
			</Col>;
<FlipMotion component={Col3}>`

Gives the warning:
Warning: Failed prop type: Invalid prop `component` of type `function` supplied to `FlipMotion`, expected `string`.

**Comment by asbjornh** [comment]
Fixed in `1.1.7` 😊
